create table if not exists guestbook_message (
    id bigint generated by default as identity primary key,
    author varchar(100) not null,
    message varchar(1000) not null,
    created_at timestamp not null
);
